### PR TITLE
[Lite] Disable webmidi (patch)

### PR DESCRIPTION
**Pull request by heke123**
26K binary size reduced, add flag disable_webmidi

### CODE REVIEW

**Comment by heke123** [comment]
@halton  @PeterWangIntel

**Comment by heke123** [comment]
As f2f discussed, let's drop this commit,   Use Peter's.

**Comment by heke123** [comment]
@PeterWangIntel,  As f2f discussed,  this patch is still useful. 
I remove the generate_modules_gypi.py part because you have committed the changes in previous PR.

**Comment by PeterWangIntel** [comment]
LGTM, thx.

**Pull request merged**
