### PR TITLE
To disable WebCL

### PR DESCRIPTION
**Pull request by PeterWangIntel**
Leverage existing flag "enable_webcl" to disable functions and exclude
related code in Blink.
Reduced size = 44K

### CODE REVIEW

**Comment by PeterWangIntel** [comment]
@heke123 @halton 
Please have a look.

**Comment by PeterWangIntel** [comment]
@heke123, thx. It'll be updated soon.

**Comment by PeterWangIntel** [comment]
@heke123

**Comment by heke123** [comment]
LGTM

**Pull request merged**
