### PR TITLE
[Lite] To resolve build problem of disabling WebMIDI

### PR DESCRIPTION
**Pull request by PeterWangIntel**

### CODE REVIEW

**Comment by PeterWangIntel** [comment]
@heke123, just for discussion

**Comment by heke123** [comment]
LGTM, as f2f discussed.

**Comment by PeterWangIntel** [comment]
@halton , 
Please help to merge. It's resolved a build problem so we can open disable_webmidi.

**Comment by heke123** [comment]
@PeterWangIntel ,  I found problems. 
the build is failed in my PC, I'm afraid maybe my patch is still needed.
I'm very curious why the build in trybot is success!  anyway, let's discuss f2f later.

**Pull request merged**
