### PR TITLE
Refine the modules_gypi_generator.py

### PR DESCRIPTION
**Pull request by PeterWangIntel**
To make it more easy to disable 'modules'

### CODE REVIEW

**Comment by PeterWangIntel** [comment]
@heke123 @halton

**Comment by halton** [comment]
I'm unable to check the diff from the github page, @heke123 could you do F2F review?

**Comment by heke123** [comment]
F2F discussed with Peter.    LGTM

**Comment by PeterWangIntel** [comment]
@halton 
Please help to merge. We've verified carefully. It's the base of following patches.

**Pull request merged**
