### PR TITLE
[Android] Fix an error in extracting WebCL kernel parameter list.

### PR DESCRIPTION
**Pull request by hujiajie**
The second argument passed to String::substring should be the length instead of the end position.

BUG=XWALK-4481

### CODE REVIEW

**Comment by hujiajie** [comment]
@chunkyan @ds-hwang PTAL, thanks

**Comment by ds-hwang** [comment]
@junmin-zhu PTAL?

**Comment by hujiajie** [comment]
@ds-hwang sorry for the late notification, but Junmin has left the project. His work has been transferred to Shaobo (chunkyan) and me.

**Comment by ds-hwang** [comment]
I see. lgtm. thx!

**Comment by rakuco** [comment]
Don't forget to roll `DEPS.xwalk`.

**Pull request merged**
