### PR TITLE
Crosswalk cocos2d optimization

### PR DESCRIPTION
**Pull request by kurli**
Contains 3 patches for cocos2d optimization and 1 patch to fix enable inspector fail issue.
One component is missing (Cocos2d engine), we will opensource it in the future, it's currently under OpenSource PDT review.
The build flag to enable this feature has been disabled by default, So it will not impact the original build.

### CODE REVIEW

**Comment by halton** [comment]
It is out-of my review ability to reivew this huge PR. I will trust game mode team can ensure everything is okay with the code(functionality, OO design, coding style and etc).

Please include someone in game mode team to give the peer review LGTM, then I'll merge it.

**Comment by kurli** [comment]
Thanks @halton , I have checked with enable_cocos2d flag enable and disable, all works.
Ping @js0701 @gaochun 
Would you please have a review?

**Comment by halton** [comment]
@gaochun, how about this one?

**Comment by kurli** [comment]
@gaochun Source/modules/modules.gypi also has no License header, So not added here.

**Comment by kurli** [comment]
Ping @js0701 @gaochun 
Updated the patch, please have a review

**Comment by halton** [comment]
Anyone can review? The lite branch will be rebase to crosswalk-14, it will affect this integration.

**Comment by kurli** [comment]
Hi @halton How about create a new branch for cocos2d optimization? And rebase to crosswalk-14 in the future?

**Comment by rakuco** [comment]
Let me add my two cents from the perspective of someone maintaining Crosswalk non-Lite, since I guess ultimately this is supposed to make its way there in the future.

* First of all, there are several coding style errors: function declarations with spaces before the  `()`s, double declaration of visibility inside classes (ie. classes with two `public:` entries whereas one of them should have been `private:`) etc.
* It's also not clear why the auto-generated bindings need to be part of the tree: aren't those files supposed to be generated as part of the build and thus be in the build directory?
* There is no mention anywhere, be it the pull request message, or commit messages, that explain what is being done here and especially _why_. There's also no JIRA ticket mentioned anywhere.
* Internal git links do not mean anything if you are upstreaming your core.
* There is *a lot* of code here. It's basically impossible for anyone to review everything being added in this pull request, and getting this into Crosswalk master is going to be difficult if there are no explanations.

**Comment by kurli** [comment]
@rakuco Thanks for your comments.
This is our first release for cocos2d optimization, Sorry for the huge patch.
Please refer our draft design doc: https://docs.google.com/document/d/1vQqUuOnI15AGFupyOi_i5giky8nOH518Yx2qs--RAXs/edit

1) For the coding style:
Most of the code are auto generated from customized cocos2d-binding-generator. It's hard to make all the generated code follow the coding style, but we will do our best to make it better.
2) Why binding code in the source tree
It's hard to integrate cocos2d-binding-generator into chrome build tool in our first version, and put these in the source tree will be better for us to debug. how about improve this in the future?
3) We will create JIRA tickets
4) We are using customized cocos2d source code, There is no repo currently in our github crosswalk-project, How about add it in the future?

**Comment by halton** [comment]
Any update on this PR? The rebasing of lite branch is kind of blocked on this PR.

**Comment by kurli** [comment]
Hi @halton 
We are currently investigating memory leak issue from this PR. Will update this when the issue resolved.
We will rebase by ourselves.

**Comment by kurli** [comment]
Updated the patch with fix memory leak issues, and added more detailed commit messages.
@js0701 @gaochun Please have a review, Thanks

**Comment by gaochun** [comment]
LGTM, thanks.

**Comment by js0701** [comment]
LGTM

**Comment by kurli** [comment]
Hi @halton Got two LGTM, Would you please have a review and merge?

**Comment by halton** [comment]
@kurli is this final PR we need wait? If yes, @d0ngjun will do the rebase for lite branch.

**Comment by kurli** [comment]
@halton Yes, it's final PR for blink-crosswalk repo.

**Pull request merged**
