### PR TITLE
Fix compiling failure when set disable_xlst=0

### PR DESCRIPTION
**Pull request by d0ngjun**
It's a gyp variable conditionalize issue, need to use
'variables-inside-variables hack' to fix it.

BUG=XWALK-4522

### CODE REVIEW

**Comment by d0ngjun** [comment]
will add size reducing info in xwalk repo.

**Comment by d0ngjun** [comment]
@heke123 @PeterWangIntel @shawngao5 please help review, thanks!

**Comment by shawngao5** [comment]
lgtm

**Comment by d0ngjun** [comment]
@halton, please help merge this fix.

**Pull request merged**
